In [1]:
#cramers method

In [1]:
import numpy as np
import math

In [32]:
sz = 3
mat = [3,4,2,-1,3,-4,2,2,5]
rhs = [5,2,-6]


In [ ]:
det(mat)

In [10]:
mat = np.array(mat).reshape(sz,sz)

In [12]:
mat

array([[ 3,  4,  2],
       [-1,  3, -4],
       [ 2,  2,  5]])

In [14]:
mat[:,0] = rhs

In [15]:
mat

array([[ 5,  4,  2],
       [ 2,  3, -4],
       [-6,  2,  5]])

In [23]:
mat.shape

AttributeError: 'list' object has no attribute 'shape'

In [33]:
def cramers_rule(sz,mat,rhs):
    mat = np.array(mat).reshape(sz,sz)
    rhs = np.array(rhs)
    base_det = np.linalg.det(mat)
    interemediate_dets = []
    roots = []
    for i in range(sz):
        new_arr = np.array(mat)
        new_arr[:,i] = rhs
        i_det = np.linalg.det(new_arr)
        interemediate_dets.append(i_det)
        roots.append(i_det/base_det)
    return interemediate_dets,roots
        
    

In [34]:
roots,int_dets = cramers_rule(sz,mat,rhs)

In [35]:
roots

[215.0000000000001, -53.00000000000003, -114.00000000000003]

In [28]:
np.array(mat).reshape((3,3))@np.array(roots)

array([ 205.,   82., -246.])

In [4]:
np.array([[0.58,0.58,0.58,0,0],[0,0,0,0.71,0.71]]).reshape(5,2)

array([[0.58, 0.58],
       [0.58, 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.71, 0.71]])

In [6]:
a = [0.58,0.58,0.58,0,0]
b = [0,0,0,0.71,0.71]
out = list(zip(a,b))

In [9]:
np.array([0,4,5,3,0]).reshape(1,5)@np.array(out)

array([[5.22, 2.13]])

In [ ]:
np.array([0,4,5,3,0]).reshape(1,5)@np.array([[0.58,0.58,0.58,0,0],[0,0,0,0.71,0.71]])